version: "3.3"
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: concellia
      POSTGRES_PASSWORD: tiyiselani
      POSTGRES_DB: database
    ports:
      - "5432:5432"

